/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author X
 */
public class rMahasiswa extends javax.swing.JFrame {
    DefaultTableModel tabModel;
    /**
     * Creates new form Mahasiswa
     */
    public rMahasiswa() throws SQLException {
        initComponents();
        showTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txnpm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txnama = new javax.swing.JTextField();
        txjk = new javax.swing.JTextField();
        txalamat = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmahasiswa = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnrefresh1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Mahasiswa");

        jLabel2.setText("NPM");

        jLabel3.setText("Nama");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Alamat");

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        tblmahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblmahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmahasiswa);

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnrefresh1.setText("Kembali");
        btnrefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefresh1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txalamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(txjk, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txnama, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txnpm, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btntambah, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(btnhapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnrefresh1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txnpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnrefresh1))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txjk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        String npm = txnpm.getText();
        if (npm.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Npm tidak boleh kosong");
            txnpm.requestFocus();
        }else if(JOptionPane.showConfirmDialog(null,"Apakah anda yakin akan menghapus data ini?",
            "Informasi",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.OK_OPTION){
        try{
            Connection connect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","mohrifqi_90492","mohamad");
            Statement statement = connect.createStatement();
            statement.executeUpdate("DELETE FROM mahasiswa_90492 WHERE npm_mahasiswa='"+npm+"'");
            BersihData();
            showTabel();
            JOptionPane.showMessageDialog(this,"Data berhasil di hapus","Success",JOptionPane.INFORMATION_MESSAGE);
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this,"Delete data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        String npm =txnpm.getText();
        String nama=txnama.getText();
        String jk =txjk.getText();
        String alamat = txalamat.getText();
        if (npm.isEmpty()&&nama.isEmpty()&&jk.isEmpty()&&alamat.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Tidak boleh ada yang kosong");
        }else if (!(new Scanner(npm).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"Npm harus angka");
            txnpm.requestFocus();
        }else{
        try{
            Connection connect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","mohrifqi_90492","mohamad");
            Statement statement = connect.createStatement();
            statement.executeUpdate("UPDATE mahasiswa_90492 SET nama_mahasiswa='"+nama+"', jenis_kelamin_mahasiswa='"+jk+"', alamat_mahasiswa='"+alamat+"' WHERE npm_mahasiswa='"+npm+"'");
                
                BersihData();
                showTabel();                
                JOptionPane.showMessageDialog(this,"Data berhasil disimpan","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Simpan data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            } 
        }
    }//GEN-LAST:event_btnsimpanActionPerformed
    private void tblmahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmahasiswaMouseClicked
        klik();
    }//GEN-LAST:event_tblmahasiswaMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        String npm =txnpm.getText();
        String nama=txnama.getText();
        String jk =txjk.getText();
        String alamat = txalamat.getText();
        if (npm.isEmpty()&&nama.isEmpty()&&jk.isEmpty()&&alamat.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Tidak boleh ada yang kosong");
        }else if (!(new Scanner(npm).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"Npm harus angka");
            txnpm.requestFocus();
        }else{
        try{
            Connection connect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","mohrifqi_90492","mohamad");
            Statement statement = connect.createStatement();
            statement.executeUpdate("insert into mahasiswa_90492(npm_mahasiswa,nama_mahasiswa,jenis_kelamin_mahasiswa,alamat_mahasiswa)"+
                    "VALUES('"+npm+"','"+nama+"','"+jk+"','"+alamat+"')");
                
                BersihData();
                showTabel();                
//                rata();
                JOptionPane.showMessageDialog(this,"Data berhasil disimpan","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Simpan data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            } 
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnrefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefresh1ActionPerformed
        setVisible(false);
        try {
            new Transaksiview().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(rMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnrefresh1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new rMahasiswa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(rMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    void simpan(){

    }
      public void showTabel() throws SQLException{
        Object[] judul_kolom = {"Npm", "Nama", "Jenis Kelamin","Alamat"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            tblmahasiswa.setModel(tabModel);
            
            Connection connect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","mohrifqi_90492","mohamad");
            Statement statement = connect.createStatement();
            tabModel.getDataVector().removeAllElements();
            ResultSet RsTabel=statement.executeQuery("SELECT * from mahasiswa_90492");  
            while(RsTabel.next()){
                Object[] data={
                    RsTabel.getString("npm_mahasiswa"),
                    RsTabel.getString("nama_mahasiswa"),
                    RsTabel.getString("jenis_kelamin_mahasiswa"),
                    RsTabel.getString("alamat_mahasiswa"),    
                };
               tabModel.addRow(data);
        
    }
    }
    void klik(){
        txnpm.setText(tabModel.getValueAt(tblmahasiswa.getSelectedRow(),0)+"");
        txnama.setText(tabModel.getValueAt(tblmahasiswa.getSelectedRow(),1)+"");
        txjk.setText(tabModel.getValueAt(tblmahasiswa.getSelectedRow(),2)+"");
        txalamat.setText(tabModel.getValueAt(tblmahasiswa.getSelectedRow(),3)+"");
        
        btnsimpan.setEnabled(true);
        btntambah.setEnabled(false);
        txnpm.setEnabled(false);
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnrefresh1;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmahasiswa;
    private javax.swing.JTextField txalamat;
    private javax.swing.JTextField txjk;
    private javax.swing.JTextField txnama;
    private javax.swing.JTextField txnpm;
    // End of variables declaration//GEN-END:variables

    private void BersihData() {
        txnpm.setText("");
        txnama.setText("");
        txjk.setText("");
        txalamat.setText("");
    }
}
