/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author X
 */
public class rSpp extends javax.swing.JFrame {
    DefaultTableModel tabModel;
    /**
     * Creates new form Mahasiswa
     */
    public rSpp() throws SQLException {
        initComponents();
        showTabel();
    }
private void BersihData() {
        txidspp.setText("");
        txnpm.setText("");
        txidbank.setText("");
//        txtanggal.setText("");
        txbulan.setText("");
        txnominal.setText("");
        txdenda.setText("");
        txstatus.setText("");
    }
public void showTabel() throws SQLException{
        Object[] judul_kolom = {"Id SPP", "NPM","Id Bank","Tanggal","Bulan","Nominal","Denda","Status" };
            tabModel=new DefaultTableModel(null,judul_kolom);
            tblspp.setModel(tabModel);
            
            Connection connect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","mohrifqi_90492","mohamad");
            Statement statement = connect.createStatement();
            tabModel.getDataVector().removeAllElements();
            ResultSet RsTabel=statement.executeQuery("SELECT * from pembayaran_spp_90492");  
            while(RsTabel.next()){
                Object[] data={
                    RsTabel.getString("id_spp"),
                    RsTabel.getString("npm_mahasiswa"),
                    RsTabel.getString("id_bank"),
                    RsTabel.getString("tanggal_spp"),
                    RsTabel.getString("bulan_spp"),
                    RsTabel.getString("npm90492_nominal_spp"),
                    RsTabel.getString("denda_spp"),
                    RsTabel.getString("konfirmasi_pembayaran_spp") 
                };
               tabModel.addRow(data);
        
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblspp = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnrefresh1 = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        txidspp = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        txnpm = new javax.swing.JTextField();
        txidbank = new javax.swing.JTextField();
        txbulan = new javax.swing.JTextField();
        txnominal = new javax.swing.JTextField();
        txdenda = new javax.swing.JTextField();
        txstatus = new javax.swing.JTextField();

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Pembayaran SPP");

        jLabel2.setText("Id SPP");

        jLabel3.setText("NPM");

        jLabel4.setText("Id Bank");

        jLabel6.setText("Bulan");

        jLabel7.setText("Nominal");

        jLabel8.setText("Denda");

        jLabel9.setText("Status");

        tblspp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblspp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsppMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblspp);

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnrefresh1.setText("Kembali");
        btnrefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefresh1ActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txidspp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txnpm, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txidbank, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txnominal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txdenda, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btntambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnhapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnrefresh1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txidspp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txnpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txidbank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txnominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txdenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnrefresh1)
                        .addGap(7, 7, 7)
                        .addComponent(btntambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnhapus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
              
        String idspp =txidspp.getText();
        String npm =txnpm.getText();
        String idbank=txidbank.getText();
//        String tanggal=txtanggal.getText();
        String bulan =txbulan.getText();
        String nominal = txnominal.getText();
        String denda = txdenda.getText();
        String status = txstatus.getText();
        
        java.util.Date tanggal = new java.util.Date();
        java.text.SimpleDateFormat TanggalFormat= new java.text.SimpleDateFormat("dd/MM/yyyy");
        String tanggal_spp=TanggalFormat.format(tanggal);
        
        if (idspp.isEmpty()&&npm.isEmpty()&&idbank.isEmpty()&&bulan.isEmpty()&&nominal.isEmpty()&&denda.isEmpty()&&status.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Tidak boleh ada yang kosong");
            txnpm.requestFocus();
            txidspp.requestFocus();
            txidbank.requestFocus();
//            txtanggal.requestFocus();
            txbulan.requestFocus();
            txnominal.requestFocus();
            txdenda.requestFocus();
            txstatus.requestFocus();
        }else if (!(new Scanner(idspp).hasNextInt())&&(new Scanner(npm).hasNextInt())&&(new Scanner(idbank).hasNextInt())
                &&(new Scanner(bulan).hasNextInt())&&(new Scanner(nominal).hasNextInt())&&(new Scanner(denda).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"Harus angka");
            txnpm.requestFocus();
            txidspp.requestFocus();
            txidbank.requestFocus();
//            txtanggal.requestFocus();
            txbulan.requestFocus();
            txnominal.requestFocus();
            txdenda.requestFocus();
            
        }else{
            try{
                Connection connect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","mohrifqi_90492","mohamad");
                Statement statement = connect.createStatement();
                statement.executeUpdate("insert into pembayaran_spp_90492(id_spp,npm_mahasiswa,id_bank,tanggal_spp,bulan_spp,npm90492_nominal_spp,denda_spp,konfirmasi_pembayaran_spp)"+
                    "VALUES('"+idspp+"','"+npm+"','"+idbank+"',to_date('"+tanggal_spp+"','dd/mm/yyyy'),'"+bulan+"','"+nominal+"','"+denda+"','"+status+"')");

                BersihData();
                showTabel();
                //                rata();
                JOptionPane.showMessageDialog(this,"Data berhasil disimpan","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Simpan data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        
        
        String idspp =txidspp.getText();
        String npm =txnpm.getText();
        String idbank=txidbank.getText();
//        String tanggal=txtanggal.getText();
        String bulan =txbulan.getText();
        String nominal = txnominal.getText();
        String denda = txdenda.getText();
        String status = txstatus.getText();
        
        java.util.Date tanggal = new java.util.Date();
        java.text.SimpleDateFormat TanggalFormat= new java.text.SimpleDateFormat("dd/MM/yyyy");
        String tanggal_spp=TanggalFormat.format(tanggal);
        
        if (idspp.isEmpty()&&npm.isEmpty()&&idbank.isEmpty()&&bulan.isEmpty()&&nominal.isEmpty()&&denda.isEmpty()&&status.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Tidak boleh ada yang kosong");
            txnpm.requestFocus();
            txidspp.requestFocus();
            txidbank.requestFocus();
//            txtanggal.requestFocus();
            txbulan.requestFocus();
            txnominal.requestFocus();
            txdenda.requestFocus();
            txstatus.requestFocus();
        }else if (!(new Scanner(idspp).hasNextInt())&&(new Scanner(npm).hasNextInt())&&(new Scanner(idbank).hasNextInt())
                &&(new Scanner(bulan).hasNextInt())&&(new Scanner(nominal).hasNextInt())&&(new Scanner(denda).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"Harus angka");
            txnpm.requestFocus();
            txidspp.requestFocus();
            txidbank.requestFocus();
//            txtanggal.requestFocus();
            txbulan.requestFocus();
            txnominal.requestFocus();
            txdenda.requestFocus();
            
        }else{
            try{
                Connection connect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","mohrifqi_90492","mohamad");
                Statement statement = connect.createStatement();
                statement.executeUpdate("UPDATE pembayaran_spp_90492 SET tanggal_spp= to_date('"+tanggal_spp+"','dd/mm/yyyy')', bulan_spp='"+bulan+"', nominal_spp='"+nominal+"',"
                        + "denda_spp='"+denda+"', konfirmasi_pembayaran_spp='"+status+"' WHERE id_spp='"+idspp+"',id_bank='"+idbank+"', npm_mahasiswa='"+npm+"'");

                BersihData();
                showTabel();
                JOptionPane.showMessageDialog(this,"Data berhasil disimpan","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Simpan data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnrefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefresh1ActionPerformed
        setVisible(false);
        try {
            new Transaksiview().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(rSpp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnrefresh1ActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        String idspp = txidspp.getText();
        if (idspp.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Npm tidak boleh kosong");
            txidspp.requestFocus();
        }else if(JOptionPane.showConfirmDialog(null,"Apakah anda yakin akan menghapus data ini?",
            "Informasi",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.OK_OPTION){
        try{
            Connection connect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","mohrifqi_90492","mohamad");
            Statement statement = connect.createStatement();
            statement.executeUpdate("DELETE FROM pembayaran_spp_90492 WHERE id_spp='"+idspp+"'");
            BersihData();
            showTabel();
            JOptionPane.showMessageDialog(this,"Data berhasil di hapus","Success",JOptionPane.INFORMATION_MESSAGE);
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this,"Delete data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tblsppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsppMouseClicked
        txidspp.setText(tabModel.getValueAt(tblspp.getSelectedRow(),0)+"");
        txnpm.setText(tabModel.getValueAt(tblspp.getSelectedRow(),1)+"");
        txidbank.setText(tabModel.getValueAt(tblspp.getSelectedRow(),2)+"");
//        txtanggal.setText(tabModel.getValueAt(tblspp.getSelectedRow(),3)+"");
        txbulan.setText(tabModel.getValueAt(tblspp.getSelectedRow(),4)+"");
        txnominal.setText(tabModel.getValueAt(tblspp.getSelectedRow(),5)+"");
        txdenda.setText(tabModel.getValueAt(tblspp.getSelectedRow(),6)+"");
        txstatus.setText(tabModel.getValueAt(tblspp.getSelectedRow(),7)+"");
        
        btnsimpan.setEnabled(true);
        btntambah.setEnabled(false);
        txidspp.setEnabled(false);
        txnpm.setEnabled(false);
        txidbank.setEnabled(false);
    }//GEN-LAST:event_tblsppMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rSpp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rSpp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rSpp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rSpp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new rSpp().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(rSpp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnrefresh1;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable tblspp;
    private javax.swing.JTextField txbulan;
    private javax.swing.JTextField txdenda;
    private javax.swing.JTextField txidbank;
    private javax.swing.JTextField txidspp;
    private javax.swing.JTextField txnominal;
    private javax.swing.JTextField txnpm;
    private javax.swing.JTextField txstatus;
    // End of variables declaration//GEN-END:variables
}
